// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/matchmaking.proto

package matchmakingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ENUMS — Strictly match your DB values
type StudyMode int32

const (
	StudyMode_QUIET         StudyMode = 0
	StudyMode_COLLABORATIVE StudyMode = 1
)

// Enum value maps for StudyMode.
var (
	StudyMode_name = map[int32]string{
		0: "QUIET",
		1: "COLLABORATIVE",
	}
	StudyMode_value = map[string]int32{
		"QUIET":         0,
		"COLLABORATIVE": 1,
	}
)

func (x StudyMode) Enum() *StudyMode {
	p := new(StudyMode)
	*p = x
	return p
}

func (x StudyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_proto_enumTypes[0].Descriptor()
}

func (StudyMode) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_proto_enumTypes[0]
}

func (x StudyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudyMode.Descriptor instead.
func (StudyMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{0}
}

type GroupSize int32

const (
	GroupSize_ONE_ON_ONE  GroupSize = 0
	GroupSize_SMALL_GROUP GroupSize = 1
)

// Enum value maps for GroupSize.
var (
	GroupSize_name = map[int32]string{
		0: "ONE_ON_ONE",
		1: "SMALL_GROUP",
	}
	GroupSize_value = map[string]int32{
		"ONE_ON_ONE":  0,
		"SMALL_GROUP": 1,
	}
)

func (x GroupSize) Enum() *GroupSize {
	p := new(GroupSize)
	*p = x
	return p
}

func (x GroupSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupSize) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_proto_enumTypes[1].Descriptor()
}

func (GroupSize) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_proto_enumTypes[1]
}

func (x GroupSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupSize.Descriptor instead.
func (GroupSize) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{1}
}

type CommunicationMethod int32

const (
	CommunicationMethod_VIDEO CommunicationMethod = 0
	CommunicationMethod_AUDIO CommunicationMethod = 1
	CommunicationMethod_CHAT  CommunicationMethod = 2
)

// Enum value maps for CommunicationMethod.
var (
	CommunicationMethod_name = map[int32]string{
		0: "VIDEO",
		1: "AUDIO",
		2: "CHAT",
	}
	CommunicationMethod_value = map[string]int32{
		"VIDEO": 0,
		"AUDIO": 1,
		"CHAT":  2,
	}
)

func (x CommunicationMethod) Enum() *CommunicationMethod {
	p := new(CommunicationMethod)
	*p = x
	return p
}

func (x CommunicationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommunicationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matchmaking_proto_enumTypes[2].Descriptor()
}

func (CommunicationMethod) Type() protoreflect.EnumType {
	return &file_proto_matchmaking_proto_enumTypes[2]
}

func (x CommunicationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommunicationMethod.Descriptor instead.
func (CommunicationMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{2}
}

// Match request sent from Laravel to Go engine
type MatchRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUID from match_requests table
	UserId    int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // Foreign key to users table
	// Matching criteria
	Subject           string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`                                              // e.g., "Physics"
	Level             string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`                                                  // beginner, intermediate, advanced
	PreferredLanguage string `protobuf:"bytes,5,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"` // e.g., "English"
	StudyStyle        string `protobuf:"bytes,6,opt,name=study_style,json=studyStyle,proto3" json:"study_style,omitempty"`                      // discussion, flashcards, silent
	Timezone          string `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`                                            // e.g., "UTC+2"
	DesiredTime       string `protobuf:"bytes,8,opt,name=desired_time,json=desiredTime,proto3" json:"desired_time,omitempty"`                   // ISO datetime string
	TimeFlexMinutes   int32  `protobuf:"varint,9,opt,name=time_flex_minutes,json=timeFlexMinutes,proto3" json:"time_flex_minutes,omitempty"`    // ± time flexibility
	// Study preferences
	StudyMode     StudyMode           `protobuf:"varint,10,opt,name=study_mode,json=studyMode,proto3,enum=matchmaking.StudyMode" json:"study_mode,omitempty"`  // QUIET or COLLABORATIVE
	GroupSize     GroupSize           `protobuf:"varint,11,opt,name=group_size,json=groupSize,proto3,enum=matchmaking.GroupSize" json:"group_size,omitempty"`  // ONE_ON_ONE or SMALL_GROUP
	Communication CommunicationMethod `protobuf:"varint,12,opt,name=communication,proto3,enum=matchmaking.CommunicationMethod" json:"communication,omitempty"` // VIDEO, AUDIO, CHAT
	// Optional custom priorities for scoring (weights)
	PriorityWeights map[string]float32 `protobuf:"bytes,13,rep,name=priority_weights,json=priorityWeights,proto3" json:"priority_weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Client metadata (optional, for debugging or ML)
	ClientVersion string `protobuf:"bytes,14,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	UserAgent     string `protobuf:"bytes,15,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MatchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MatchRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *MatchRequest) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

func (x *MatchRequest) GetStudyStyle() string {
	if x != nil {
		return x.StudyStyle
	}
	return ""
}

func (x *MatchRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *MatchRequest) GetDesiredTime() string {
	if x != nil {
		return x.DesiredTime
	}
	return ""
}

func (x *MatchRequest) GetTimeFlexMinutes() int32 {
	if x != nil {
		return x.TimeFlexMinutes
	}
	return 0
}

func (x *MatchRequest) GetStudyMode() StudyMode {
	if x != nil {
		return x.StudyMode
	}
	return StudyMode_QUIET
}

func (x *MatchRequest) GetGroupSize() GroupSize {
	if x != nil {
		return x.GroupSize
	}
	return GroupSize_ONE_ON_ONE
}

func (x *MatchRequest) GetCommunication() CommunicationMethod {
	if x != nil {
		return x.Communication
	}
	return CommunicationMethod_VIDEO
}

func (x *MatchRequest) GetPriorityWeights() map[string]float32 {
	if x != nil {
		return x.PriorityWeights
	}
	return nil
}

func (x *MatchRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MatchRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// Match result returned by Go engine
type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // UUID of match_results
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`   // Optional: match score (0–100)
	Partner       *MatchPartner          `protobuf:"bytes,5,opt,name=partner,proto3" json:"partner,omitempty"` // Basic info about matched user (if any)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_proto_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *MatchResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MatchResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MatchResponse) GetPartner() *MatchPartner {
	if x != nil {
		return x.Partner
	}
	return nil
}

// Optional preview of the matched partner (sanitized)
type MatchPartner struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level             string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	PreferredLanguage string                 `protobuf:"bytes,3,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	StudyStyle        string                 `protobuf:"bytes,4,opt,name=study_style,json=studyStyle,proto3" json:"study_style,omitempty"`
	ReputationScore   float32                `protobuf:"fixed32,5,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchPartner) Reset() {
	*x = MatchPartner{}
	mi := &file_proto_matchmaking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPartner) ProtoMessage() {}

func (x *MatchPartner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPartner.ProtoReflect.Descriptor instead.
func (*MatchPartner) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *MatchPartner) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchPartner) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *MatchPartner) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

func (x *MatchPartner) GetStudyStyle() string {
	if x != nil {
		return x.StudyStyle
	}
	return ""
}

func (x *MatchPartner) GetReputationScore() float32 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

var File_proto_matchmaking_proto protoreflect.FileDescriptor

const file_proto_matchmaking_proto_rawDesc = "" +
	"\n" +
	"\x17proto/matchmaking.proto\x12\vmatchmaking\"\xcc\x05\n" +
	"\fMatchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12-\n" +
	"\x12preferred_language\x18\x05 \x01(\tR\x11preferredLanguage\x12\x1f\n" +
	"\vstudy_style\x18\x06 \x01(\tR\n" +
	"studyStyle\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12!\n" +
	"\fdesired_time\x18\b \x01(\tR\vdesiredTime\x12*\n" +
	"\x11time_flex_minutes\x18\t \x01(\x05R\x0ftimeFlexMinutes\x125\n" +
	"\n" +
	"study_mode\x18\n" +
	" \x01(\x0e2\x16.matchmaking.StudyModeR\tstudyMode\x125\n" +
	"\n" +
	"group_size\x18\v \x01(\x0e2\x16.matchmaking.GroupSizeR\tgroupSize\x12F\n" +
	"\rcommunication\x18\f \x01(\x0e2 .matchmaking.CommunicationMethodR\rcommunication\x12Y\n" +
	"\x10priority_weights\x18\r \x03(\v2..matchmaking.MatchRequest.PriorityWeightsEntryR\x0fpriorityWeights\x12%\n" +
	"\x0eclient_version\x18\x0e \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0f \x01(\tR\tuserAgent\x1aB\n" +
	"\x14PriorityWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xad\x01\n" +
	"\rMatchResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x123\n" +
	"\apartner\x18\x05 \x01(\v2\x19.matchmaking.MatchPartnerR\apartner\"\xb8\x01\n" +
	"\fMatchPartner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12-\n" +
	"\x12preferred_language\x18\x03 \x01(\tR\x11preferredLanguage\x12\x1f\n" +
	"\vstudy_style\x18\x04 \x01(\tR\n" +
	"studyStyle\x12)\n" +
	"\x10reputation_score\x18\x05 \x01(\x02R\x0freputationScore*)\n" +
	"\tStudyMode\x12\t\n" +
	"\x05QUIET\x10\x00\x12\x11\n" +
	"\rCOLLABORATIVE\x10\x01*,\n" +
	"\tGroupSize\x12\x0e\n" +
	"\n" +
	"ONE_ON_ONE\x10\x00\x12\x0f\n" +
	"\vSMALL_GROUP\x10\x01*5\n" +
	"\x13CommunicationMethod\x12\t\n" +
	"\x05VIDEO\x10\x00\x12\t\n" +
	"\x05AUDIO\x10\x01\x12\b\n" +
	"\x04CHAT\x10\x022[\n" +
	"\x12MatchmakingService\x12E\n" +
	"\fRequestMatch\x12\x19.matchmaking.MatchRequest\x1a\x1a.matchmaking.MatchResponseBLZJgithub.com/el-mohandes/studysync-matchmaking-engine/internal/matchmakingpbb\x06proto3"

var (
	file_proto_matchmaking_proto_rawDescOnce sync.Once
	file_proto_matchmaking_proto_rawDescData []byte
)

func file_proto_matchmaking_proto_rawDescGZIP() []byte {
	file_proto_matchmaking_proto_rawDescOnce.Do(func() {
		file_proto_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matchmaking_proto_rawDesc), len(file_proto_matchmaking_proto_rawDesc)))
	})
	return file_proto_matchmaking_proto_rawDescData
}

var file_proto_matchmaking_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_matchmaking_proto_goTypes = []any{
	(StudyMode)(0),           // 0: matchmaking.StudyMode
	(GroupSize)(0),           // 1: matchmaking.GroupSize
	(CommunicationMethod)(0), // 2: matchmaking.CommunicationMethod
	(*MatchRequest)(nil),     // 3: matchmaking.MatchRequest
	(*MatchResponse)(nil),    // 4: matchmaking.MatchResponse
	(*MatchPartner)(nil),     // 5: matchmaking.MatchPartner
	nil,                      // 6: matchmaking.MatchRequest.PriorityWeightsEntry
}
var file_proto_matchmaking_proto_depIdxs = []int32{
	0, // 0: matchmaking.MatchRequest.study_mode:type_name -> matchmaking.StudyMode
	1, // 1: matchmaking.MatchRequest.group_size:type_name -> matchmaking.GroupSize
	2, // 2: matchmaking.MatchRequest.communication:type_name -> matchmaking.CommunicationMethod
	6, // 3: matchmaking.MatchRequest.priority_weights:type_name -> matchmaking.MatchRequest.PriorityWeightsEntry
	5, // 4: matchmaking.MatchResponse.partner:type_name -> matchmaking.MatchPartner
	3, // 5: matchmaking.MatchmakingService.RequestMatch:input_type -> matchmaking.MatchRequest
	4, // 6: matchmaking.MatchmakingService.RequestMatch:output_type -> matchmaking.MatchResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_matchmaking_proto_init() }
func file_proto_matchmaking_proto_init() {
	if File_proto_matchmaking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matchmaking_proto_rawDesc), len(file_proto_matchmaking_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matchmaking_proto_goTypes,
		DependencyIndexes: file_proto_matchmaking_proto_depIdxs,
		EnumInfos:         file_proto_matchmaking_proto_enumTypes,
		MessageInfos:      file_proto_matchmaking_proto_msgTypes,
	}.Build()
	File_proto_matchmaking_proto = out.File
	file_proto_matchmaking_proto_goTypes = nil
	file_proto_matchmaking_proto_depIdxs = nil
}
