// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/matchmaking.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	TimeSlot      string                 `protobuf:"bytes,3,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MatchRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MatchRequest) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *MatchRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_proto_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *MatchResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *MatchResponse) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *MatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_matchmaking_proto protoreflect.FileDescriptor

const file_proto_matchmaking_proto_rawDesc = "" +
	"\n" +
	"\x17proto/matchmaking.proto\x12\vmatchmaking\"t\n" +
	"\fMatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1b\n" +
	"\ttime_slot\x18\x03 \x01(\tR\btimeSlot\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\"b\n" +
	"\rMatchResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2[\n" +
	"\x12MatchmakingService\x12E\n" +
	"\fRequestMatch\x12\x19.matchmaking.MatchRequest\x1a\x1a.matchmaking.MatchResponseBDZBstudysync-matchmaking-engine/internal/pb;pbb\x06proto3"

var (
	file_proto_matchmaking_proto_rawDescOnce sync.Once
	file_proto_matchmaking_proto_rawDescData []byte
)

func file_proto_matchmaking_proto_rawDescGZIP() []byte {
	file_proto_matchmaking_proto_rawDescOnce.Do(func() {
		file_proto_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matchmaking_proto_rawDesc), len(file_proto_matchmaking_proto_rawDesc)))
	})
	return file_proto_matchmaking_proto_rawDescData
}

var file_proto_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_matchmaking_proto_goTypes = []any{
	(*MatchRequest)(nil),  // 0: matchmaking.MatchRequest
	(*MatchResponse)(nil), // 1: matchmaking.MatchResponse
}
var file_proto_matchmaking_proto_depIdxs = []int32{
	0, // 0: matchmaking.MatchmakingService.RequestMatch:input_type -> matchmaking.MatchRequest
	1, // 1: matchmaking.MatchmakingService.RequestMatch:output_type -> matchmaking.MatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_matchmaking_proto_init() }
func file_proto_matchmaking_proto_init() {
	if File_proto_matchmaking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matchmaking_proto_rawDesc), len(file_proto_matchmaking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matchmaking_proto_goTypes,
		DependencyIndexes: file_proto_matchmaking_proto_depIdxs,
		MessageInfos:      file_proto_matchmaking_proto_msgTypes,
	}.Build()
	File_proto_matchmaking_proto = out.File
	file_proto_matchmaking_proto_goTypes = nil
	file_proto_matchmaking_proto_depIdxs = nil
}
